<a href="https://colab.research.google.com/github/Leela-sai-krishna-Thota/Basic_ML/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Assignment1

1.perform arithmetic operations on Numpy arrays


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0.2        0.33333333 0.42857143]
[1 2 3]
[   1   64 2187]




---



2.write a script to compute the mean and standard deviation of numpy array


In [ ]:
a=np.array([1,2,3])
print(np.mean(a))
print(np.std(a))

2.0
0.816496580927726


3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [9]:
s=np.array(range(10,50,5))
print(s)

[10 15 20 25 30 35 40 45]


4.Reshape the array into a 2x4 matrix.


In [ ]:
rs=s.reshape(2,4)
print(rs)

[[10 15 20 25]
 [30 35 40 45]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]): • Extract the sub-matrix containing the last two rows and first two columns. • Replace all elements greater than 4 with 0.

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Sub matrix = {arr[1:,:2]}')
arr[arr>4]=0
print(f'Modified Array = {arr}')

Sub matrix = [[4 5]
 [7 8]]
Modified Array = [[1 2 3]
 [4 0 0]
 [0 0 0]]


6.Create two 1D arrays: • a = np.array([1, 2, 3]) • b = np.array([4, 5, 6]) • Perform element-wise addition, multiplication, and division.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f'Additon = {a+b}')
print(f'Multiplication = {a*b}')
print(f'Division = {a/b}')

Additon = [5 7 9]
Multiplication = [ 4 10 18]
Division = [0.25 0.4  0.5 ]


7.Create a random NumPy array of size (4, 4). Compute: • Mean of each column. • Maximum value of the entire array. • Sum of all elements.

In [5]:
a = np.random.rand(4,4)
print(f'Mean of Column = {np.mean(a,axis=0)}')
print(f'Max value = {np.max(a)}')
print(f'Sum = {np.sum(a)}')


Mean of Column = [0.64363349 0.44929376 0.39488192 0.24592909]
Max value = 0.9633485201474498
Sum = 6.934953105858887


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [6]:
arr = np.array([1, 2, 3, 4])
print(f'Modified Arr = {2*(arr+10)}')


Modified Arr = [22 24 26 28]


9.Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following: • Extract the second "layer" (i.e., the second 2D array) in the first dimension. • Extract the first two rows and the last three columns from each "layer." • Replace all elements divisible by 3 with -1.

In [7]:
arr = np.random.randint(1,100,(3,4,5))
print(f'Second 2D Arr = {arr[1]}')
print(f'Sub Arr = {arr[0,:2,-3:]}')
arr[arr%3==0]=-1
print(f'Modified Arr = {arr}')

Second 2D Arr = [[47 32 88 65 12]
 [95 25 79 78 69]
 [27 51 66 35 77]
 [42 58 53  3 47]]
Sub Arr = [[50 97 66]
 [64 72 24]]
Modified Arr = [[[89 34 50 97 -1]
  [-1 46 64 -1 -1]
  [97 14 11 86 38]
  [20 -1 56 73 89]]

 [[47 32 88 65 -1]
  [95 25 79 -1 -1]
  [-1 -1 -1 35 77]
  [-1 58 53 -1 47]]

 [[95 38 -1 -1 -1]
  [59 20 -1  8  5]
  [34 92 -1 14 41]
  [62 -1 86 -1 23]]]


10.Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20. Perform the following: • Subtract the mean of each row from its respective elements (row-wise normalization). • Create a new array by squaring all the elements in arr. • Find the indices of the top 3 maximum values in the entire array.

In [8]:
arr = np.random.randint(1,20,(3,3))
print(f'Normalized Arr = {arr-np.mean(arr,axis=1,keepdims=True)}')
sqa = np.square(arr)
print(f'Square Arr = {sqa}')
print(f'Max Indices = {np.argsort(arr.flatten())[-3:]}')

Normalized Arr = [[-7.66666667 10.33333333 -2.66666667]
 [ 4.         -1.         -3.        ]
 [-0.66666667  7.33333333 -6.66666667]]
Square Arr = [[  1 361  36]
 [169  64  36]
 [ 49 225   1]]
Max Indices = [3 7 1]
